language: node_js
node_js:
    - "4"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
    - npm install gulp xvfb-maybe electron-prebuilt .

cache:
  directories:
    - node_modules

before_script:
  - npm install -g gulp
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 -extension RANDR &

script:
    - gulp
    - xvfb-maybe npm test
